feat: added testing phase in buildspec

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -4,26 +4,39 @@ phases:
   install:
     runtime-versions:
       nodejs: 14
+    commands:
+      - npm install -g jest
   pre_build:
     commands:
       - echo "Installing dependencies..."
       - npm install
+      - npm install aws-sdk-mock --save-dev
   build:
     commands:
-      - echo "Zipping Lambda functions..."
+      - echo "Running tests and zipping Lambda functions..."
       - mkdir -p dist
       - |
         for func in functions/*; do
           if [ -d "$func" ]; then
             func_name=$(basename "$func")
             echo "Processing $func_name..."
-            (
-              cd "$func" || exit 1
-              zip -r "../../dist/$func_name.zip" index.js ../../node_modules
-            )
-            if [ $? -ne 0 ]; then
-              echo "Error zipping $func_name"
-              exit 1
+            
+            # Run tests for this function
+            jest tests/${func_name}.test.js
+            
+            if [ $? -eq 0 ]; then
+              echo "Tests passed for $func_name. Zipping and preparing for deployment..."
+              (
+                cd "$func" || exit 1
+                zip -r "../../dist/$func_name.zip" index.js ../../node_modules
+              )
+              if [ $? -ne 0 ]; then
+                echo "Error zipping $func_name"
+                exit 1
+              fi
+              echo "$func_name" >> ../successful_tests.txt
+            else
+              echo "Tests failed for $func_name. Skipping deployment."
             fi
           fi
         done
@@ -33,14 +46,19 @@ phases:
       - aws s3 cp dist s3://${S3_BUCKET_NAME} --recursive
       - echo "Updating Lambda functions..."
       - |
-        for zip in dist/*.zip; do
-          func_name=$(basename "$zip" .zip)
-          aws lambda update-function-code --function-name ${func_name} --s3-bucket ${S3_BUCKET_NAME} --s3-key $(basename "$zip")
-          if [ $? -ne 0 ]; then
-            echo "Error updating Lambda function $func_name"
-            exit 1
-          fi
-        done
+        if [ -f successful_tests.txt ]; then
+          while IFS= read -r func_name
+          do
+            echo "Updating $func_name..."
+            aws lambda update-function-code --function-name ${func_name} --s3-bucket ${S3_BUCKET_NAME} --s3-key ${func_name}.zip
+            if [ $? -ne 0 ]; then
+              echo "Error updating Lambda function $func_name"
+              exit 1
+            fi
+          done < successful_tests.txt
+        else
+          echo "No functions passed tests. Skipping deployment."
+        fi
 
 artifacts:
   files:
